config/routes.rb
Rails.application.routes.draw do

  get "/about" => "home#about"

  get "/home" => "home#index"

  resources :posts do
    get :search, on: :collection
   patch :mark_done, on: :member
   post :approve
    resources :comments, only: [:create, :destroy]
  end
  resources :comments
  resources :users, only:[:new, :create, :edit, :update]
  resources :password_resets

  resources :sessions, only:[:new, :create] do
  delete :destroy, on: :collection
  end

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end

      can :manage, Post, :user_id => user.id

      can :manage, Comment, :user_id => user.id
      can :destroy, Comment do |comm|
        comm.post.user_id == user.id 
      end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :post
  validates :title, presence:   true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body, presence:   true,
            uniqueness: { case_sensitive: false }


end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :categories
  belongs_to :user

  validates :title, presence:   true,
  uniqueness: { case_sensitive: false },
  length:     {minimum: 3, maximum: 255}

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")||
    where("body ILIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  validates :password, length:{minimum: 6}, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
  uniqueness: true,
  format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  before_create {generate_token(auth_token)}


  def full_name
    "#{first_name} #{last_name}"
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while User.exists?(column => self[column])
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
      @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def sign_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  load_and_authorize_resource :post
  load_and_authorize_resource :comment, through: :post

  # def new
  #   @comment = Comment.new
  # end
  def create
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post), notice: "Comment Created"
    else
      render "/posts/show"
    end
  end

  # def index
  #   @comments = Comment.all
  # end
  # def show
  #   @comment = Comment.find params[:id]
  # end
  # def edit
  #   @comment = Comment.find params[:id]
  # end
  # def update
  #   @comment = Comment.find params[:id]
  #   comment_params = params.require(:comment).permit([:body])
  #   if @comment.update comment_params
  #     redirect_to comment_path(@comment), notice: "Comment Updated!"
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    if @comment.destroy
    redirect_to post_path(params[:post_id]), notice: "Comment Deleted!"
  else
    flash[alert] = "You are not the owner of the comment.Access denied!"
    render "/posts/show"
  end
end

private

def comment_params
  comment_params = params.require(:comment).permit(:body)
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def about

   end

   def index
      
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, except:[:index, :show]
  load_and_authorize_resource

    def index
      if params[:search]
        @posts = Post.search(params[:search]).paginate(:page => params[:page], :per_page => 15      ).order("id DESC")
      else
        @posts = Post.paginate(:page => params[:page], :per_page => 15  )
      end
    end

    def show
      @comment = Comment.new
    end

    def create
      @post = Post.new post_params
      @post.user = current_user
      if @post.save
        redirect_to posts_path, notice: "Post Created"
      else
        render :new
      end
    end

    def new
      if user_signed_in?
        @post = Post.new
      else
        redirect_to new_session_path, alert: "You are not signed in!"
      end
    end

    def edit

    end

    def update
      if @post.update post_params
        redirect_to post_path(@post), notice: "Post Updated"
      else
        render :edit
      end
    end


    def destroy
      @post.destroy
      redirect_to posts_path
    end

    private

    def post_params
      post_params = params.require(:post).permit(:title, :body)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path, notice: "Signed in"
    else
      flash[:alert] = "Wrong Credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:show,:edit,:update,:edit_password,:update_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path,
      notice: "User Created!"
    else
      flash[:alert] = "User Created!"
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update user_params
      redirect_to posts_path, notice: "Update successfully"
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,:password, :password_digest)
  end

  def find_user
    @user = User.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<!-- <h1>Edit Comments</h1>
<%if @comment.errors.any? %>
<ul>
  <% @comment.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @comment do |f| %>
<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %> -->

app/views/comments/index.html.erb
<!-- <h1>All Comments</h1>

<% @comments.each do |comment| %>
<div>
  <h2><%= link_to comment.body,comment_path(comment) %></h2>
  <p><%= comment.body %></p> -->
  <!-- <hr />
</div>
<% end %> -->

app/views/comments/new.html.erb
<!-- <h1>Create New Comments</h1>
<%if @comment.errors.any? %>
<ul>
  <% @comment.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @comment do |f| %>
<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<%= f.submit %>
<% end %> -->

app/views/comments/show.html.erb
<!-- <p><%= @comment.body %></p>
<p><%=@comment.created_at%></p>
<%= link_to "Edit", edit_comment_path(@comment) %>
<%= link_to "Delete", comment_path(@comment), method: :delete,
data: {confirm: "Are you sure?"} %> -->

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="post-container">
  <% if @post.errors.full_messages.size > 0 %>
  <div class="alert"><%= @post.errors.full_messages.join(",") %></div>
  <% end %>
</div>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <h1>All Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title,post_path(post) %></td>
        <td><%= post.body.slice(0..25)+".." %></td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="post-container">
  <% if @post.errors.full_messages.size > 0 %>
  <div class="alert"><%= @post.errors.full_messages.join(",") %></div>
  <% end %>
</div>
<div class="post-container">
  <%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div>
    <%= f.label :category_id %>
    <%= f.collection_select(:category_id, Category.order(:title),:id, :title) %>
  </div>
  <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %></h1>
  <p><%= @post.body %></p>
  <p><%=@post.created_at%></p>
  <%if can? :edit, @post%>
    <%= link_to "Edit", edit_post_path(@post) %>
    <% end %>
    <% if can? :destroy, @post %>
    <%= link_to "Delete", post_path(@post), method: :delete,
  data: {confirm: "Are you sure?"} %>
  <% end %>
</div>
<div class="container">
  <h2>Comments</h2>
  <h3>Add your Comments here</h3>

  <%= @comment.errors.full_messages.join(" ,") %>

  <%= form_for [@post, @comment] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
    <%= f.submit %>
  <% end %>
</div>
<div class="container">
  <% @post.comments.each do |comm| %>
  <%= comm.body %>
  <%= link_to "Delete", post_comment_path(@post, comm), method: :delete, data:{confirm: "Are you sure?"}%>
  <br />
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>Update Profile</h1>
  <%= simple_form_for @user do |f| %>
  <%= f.input  :first_name%>
  <%= f.input :last_name%>
  <%= f.input  :email%>
  <%= f.input  :password%>
  <%= f.input :password_confirmation%>
  <%= f.button :submit %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign up</h1>
    <%= @user.errors.full_messages.join(" ,") %>
  <%= simple_form_for @user do |f| %>
    <%= f.input  :first_name%>
    <%= f.input  :last_name%>
    <%= f.input  :email%>
    <%= f.input :password%>
    <%= f.input :password_confirmation%>
  <%= f.button :submit %>
  <% end %>
</div>