config/routes.rb
Rails.application.routes.draw do

  get "/about" => "home#about"

  get "/home" => "home#index"

  resources :posts do
    get :search, on: :collection
   patch :mark_done, on: :member
   post :approve
    resources :comments, only: [:create, :destroy]
  end
  resources :comments
  resources :users, only:[:new, :create, :edit, :update]
  resources :password_resets

  resources :sessions, only:[:new, :create] do
  delete :destroy, on: :collection
  end

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end

      can :manage, Post, :user_id => user.id

      can :manage, Comment, :user_id => user.id
      can :destroy, Comment do |comm|
        comm.post.user_id == user.id 
      end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :post
  validates :title, presence:   true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body, presence:   true,
            uniqueness: { case_sensitive: false }


end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :categories
  belongs_to :user

  validates :title, presence:   true,
  uniqueness: { case_sensitive: false },
  length:     {minimum: 3, maximum: 255}

  def self.search(search)
    where("title ILIKE ?", "%#{search}%")||
    where("body ILIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  validates :password, length:{minimum: 6}, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
  uniqueness: true,
  format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  before_create {generate_token(auth_token)}


  def full_name
    "#{first_name} #{last_name}"
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while User.exists?(column => self[column])
end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  load_and_authorize_resource :post
  load_and_authorize_resource :comment, through: :post

  # def new
  #   @comment = Comment.new
  # end
  def create
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post), notice: "Comment Created"
    else
      render "/posts/show"
    end
  end

  # def index
  #   @comments = Comment.all
  # end
  # def show
  #   @comment = Comment.find params[:id]
  # end
  # def edit
  #   @comment = Comment.find params[:id]
  # end
  # def update
  #   @comment = Comment.find params[:id]
  #   comment_params = params.require(:comment).permit([:body])
  #   if @comment.update comment_params
  #     redirect_to comment_path(@comment), notice: "Comment Updated!"
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    if @comment.destroy
    redirect_to post_path(params[:post_id]), notice: "Comment Deleted!"
  else
    flash[alert] = "You are not the owner of the comment.Access denied!"
    render "/posts/show"
  end
end

private

def comment_params
  comment_params = params.require(:comment).permit(:body)
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def about

   end

   def index
      
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, except:[:index, :show]
  load_and_authorize_resource

    def index
      if params[:search]
        @posts = Post.search(params[:search]).paginate(:page => params[:page], :per_page => 15      ).order("id DESC")
      else
        @posts = Post.paginate(:page => params[:page], :per_page => 15  )
      end
    end

    def show
      @comment = Comment.new
    end

    def create
      @post = Post.new post_params
      @post.user = current_user
      if @post.save
        redirect_to posts_path, notice: "Post Created"
      else
        render :new
      end
    end

    def new
      if user_signed_in?
        @post = Post.new
      else
        redirect_to new_session_path, alert: "You are not signed in!"
      end
    end

    def edit

    end

    def update
      if @post.update post_params
        redirect_to post_path(@post), notice: "Post Updated"
      else
        render :edit
      end
    end


    def destroy
      @post.destroy
      redirect_to posts_path
    end

    private

    def post_params
      post_params = params.require(:post).permit(:title, :body)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:show,:edit,:update,:edit_password,:update_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path,
      notice: "User Created!"
    else
      flash[:alert] = "User Created!"
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update user_params
      redirect_to posts_path, notice: "Update successfully"
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,:password, :password_digest)
  end

  def find_user
    @user = User.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
  <title>Blog</title>
  <%#= stylesheet_link_tag "main" %>
  <%#= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- <a class="nav-left" href="#"><%#= image_tag "Drawing"%></a> -->
    <!-- <a class="navbar-brand navbar-left" href="#">My Blog</a>
    <li><a href="/home">Home</a></li>
    <li><a href="/about">About</a></li> -->
    <a class="navbar-brand navbar-left" href="#">My Blog</a>
    <%= form_tag(posts_path, :method => "get", id: "search-form",class:"navbar-brand navbar-left",role: "search") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
    <%= submit_tag "Search",:name => nil, class: "btn btn-default" %>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "New Posts", new_post_path %></li>
    <li><%= link_to "All Posts", posts_path %> </li>
    <li><%= link_to "Sign up", new_user_path %></li>
      <% if user_signed_in? %>
      <li>Hello <%= User.find(session[:user_id]).first_name %> </li>
      <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Sign in", new_session_path %></li>
      <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
  </ul>
</nav>
</div>

<div>
  <% if notice %>
  <div class="alert fade in alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4><%= notice %></h4>
  </div>

  <% elsif alert %>
  <div class="alert fade in alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4><%= alert %></h4>
  </div>
  <% end %>
</div>

<%= yield %>

</body>
</html>